import XCTest
@testable import OpenWhisper

final class OpenWhisperTests: XCTestCase {
    func testModelSourceTitles() throws {
        XCTAssertEqual(ModelSource.bundledTiny.title, "Bundled tiny model")
        XCTAssertEqual(ModelSource.customPath.title, "Custom local model")
    }

    func testModelSourceAllCases() throws {
        let allCases = ModelSource.allCases.map { $0.title }
        XCTAssertFalse(allCases.isEmpty)
    }

    func testHotkeySupportedKeyValidation() throws {
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("space"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("F12"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("z"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("home"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("pgdn"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("pg up key"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("pg dn key"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("⇞"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("⇟"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("pg down"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("page down"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("f24"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("page-up"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("left arrow"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("left key"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("return key"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("esc key"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("␛"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("insert"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("insert key"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("help"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("help key"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("section"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("§"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("space key"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("tab key"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("home key"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("numpad0"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("kp0"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("num9"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("keypadenter"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("⌧"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("numpad ."))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("numpad ,"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("numpad +"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("keypad -"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("globe"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("🌐"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("🌐︎"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("cmd+shift+space"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("cmd shift space"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("cmd\u{00A0}shift\u{00A0}space"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("meta+space"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("super-shift-f6"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("command-shift-page-down"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("⌘ + ⇧ + f6"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("⌘＋⇧＋space"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("cmd, shift, space"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("command/shift/space"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("⌘⇧space"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("⌃⌥return"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("commandshiftspace"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("ctrlaltdelete"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("return or enter"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("enter-or-return"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("backquote"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("quote left"))
        XCTAssertFalse(HotkeyDisplay.isSupportedKey(""))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("capslock"))
        XCTAssertTrue(HotkeyDisplay.isSupportedKey("caps lock"))
        XCTAssertFalse(HotkeyDisplay.isSupportedKey("foo"))
    }

    func testHotkeyCanonicalAliases() throws {
        XCTAssertEqual(HotkeyDisplay.canonicalKey("spacebar"), "space")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("space key"), "space")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("tab key"), "tab")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("␣"), "space")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("enter"), "return")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("return key"), "return")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("↩"), "return")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("↵"), "return")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("⏎"), "return")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("esc"), "escape")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("esc key"), "escape")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("⎋"), "escape")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("␛"), "escape")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("delete key"), "delete")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("backspace"), "delete")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("⌫"), "delete")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("⌦"), "forwarddelete")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("insert"), "insert")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("insert key"), "insert")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("ins"), "insert")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("help"), "help")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("help key"), "help")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("section"), "section")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("§"), "section")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("caps"), "capslock")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("caps lock"), "capslock")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("caps-lock"), "capslock")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("globe"), "fn")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("🌐"), "fn")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("🌐︎"), "fn")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("←"), "left")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("left arrow"), "left")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("→"), "right")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("right arrow"), "right")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("↑"), "up")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("↓"), "down")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("left key"), "left")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("home key"), "home")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("end key"), "end")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("page-up"), "pageup")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("pg up key"), "pageup")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("pg dn key"), "pagedown")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("⇞"), "pageup")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("⇟"), "pagedown")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("pg down"), "pagedown")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("page down"), "pagedown")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("numpad0"), "keypad0")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("kp0"), "keypad0")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("num9"), "keypad9")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("numpad enter"), "keypadenter")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("numpad ."), "keypaddecimal")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("numpad ,"), "keypadcomma")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("numpad +"), "keypadplus")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("numpad clear"), "keypadclear")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("clear"), "keypadclear")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("⌧"), "keypadclear")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("keypad -"), "keypadminus")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("cmd+shift+space"), "space")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("cmd shift space"), "space")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("cmd\u{00A0}shift\u{00A0}space"), "space")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("meta+space"), "space")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("super-shift-f6"), "f6")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("command-shift-page-down"), "pagedown")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("⌘ + ⇧ + f6"), "f6")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("⌘＋⇧＋space"), "space")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("cmd, shift, space"), "space")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("command/shift/space"), "space")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("⌘⇧space"), "space")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("⌃⌥return"), "return")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("commandshiftspace"), "space")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("ctrlaltdelete"), "delete")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("return or enter"), "return")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("enter-or-return"), "return")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("backquote"), "backtick")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("quote left"), "backtick")
        XCTAssertEqual(HotkeyDisplay.canonicalKey("grave key"), "backtick")
    }

    func testHotkeyDisplayForKeypadKeys() throws {
        XCTAssertEqual(HotkeyDisplay.displayKey("keypad0"), "Num0")
        XCTAssertEqual(HotkeyDisplay.displayKey("numpadplus"), "Num+")
        XCTAssertEqual(HotkeyDisplay.displayKey("keypadcomma"), "Num,")
        XCTAssertEqual(HotkeyDisplay.displayKey("keypadenter"), "NumEnter")
        XCTAssertEqual(HotkeyDisplay.displayKey("return"), "Return/Enter")
        XCTAssertEqual(HotkeyDisplay.displayKey("insert"), "Insert")
        XCTAssertEqual(HotkeyDisplay.displayKey("help"), "Help")
        XCTAssertEqual(HotkeyDisplay.displayKey("section"), "§")
        XCTAssertEqual(HotkeyDisplay.displayKey("fn"), "Fn/Globe")
        XCTAssertEqual(HotkeyDisplay.displayKey("equals"), "+")
    }
}