import Testing
@testable import OpenWhisper

@Suite("OpenWhisper")
struct OpenWhisperSwiftTests {
    @Test
    func modelSourceTitles() {
        #expect(ModelSource.bundledTiny.title == "Bundled tiny model")
        #expect(ModelSource.customPath.title == "Custom local model")
    }

    @Test
    func modelSourceAllCases() {
        let allCases = ModelSource.allCases.map { $0.title }
        #expect(!allCases.isEmpty)
    }

    @Test
    func hotkeySupportedKeyValidation() {
        #expect(HotkeyDisplay.isSupportedKey("space"))
        #expect(HotkeyDisplay.isSupportedKey("F12"))
        #expect(HotkeyDisplay.isSupportedKey("z"))
        #expect(HotkeyDisplay.isSupportedKey("home"))
        #expect(HotkeyDisplay.isSupportedKey("pgdn"))
        #expect(HotkeyDisplay.isSupportedKey("pg up key"))
        #expect(HotkeyDisplay.isSupportedKey("pg dn key"))
        #expect(HotkeyDisplay.isSupportedKey("⇞"))
        #expect(HotkeyDisplay.isSupportedKey("⇟"))
        #expect(HotkeyDisplay.isSupportedKey("pg down"))
        #expect(HotkeyDisplay.isSupportedKey("page down"))
        #expect(HotkeyDisplay.isSupportedKey("f24"))
        #expect(HotkeyDisplay.isSupportedKey("page-up"))
        #expect(HotkeyDisplay.isSupportedKey("left arrow"))
        #expect(HotkeyDisplay.isSupportedKey("left key"))
        #expect(HotkeyDisplay.isSupportedKey("return key"))
        #expect(HotkeyDisplay.isSupportedKey("esc key"))
        #expect(HotkeyDisplay.isSupportedKey("␛"))
        #expect(HotkeyDisplay.isSupportedKey("insert"))
        #expect(HotkeyDisplay.isSupportedKey("insert key"))
        #expect(HotkeyDisplay.isSupportedKey("help"))
        #expect(HotkeyDisplay.isSupportedKey("help key"))
        #expect(HotkeyDisplay.isSupportedKey("section"))
        #expect(HotkeyDisplay.isSupportedKey("§"))
        #expect(HotkeyDisplay.isSupportedKey("space key"))
        #expect(HotkeyDisplay.isSupportedKey("tab key"))
        #expect(HotkeyDisplay.isSupportedKey("home key"))
        #expect(HotkeyDisplay.isSupportedKey("numpad0"))
        #expect(HotkeyDisplay.isSupportedKey("kp0"))
        #expect(HotkeyDisplay.isSupportedKey("num9"))
        #expect(HotkeyDisplay.isSupportedKey("keypadenter"))
        #expect(HotkeyDisplay.isSupportedKey("⌧"))
        #expect(HotkeyDisplay.isSupportedKey("numpad ."))
        #expect(HotkeyDisplay.isSupportedKey("numpad ,"))
        #expect(HotkeyDisplay.isSupportedKey("numpad +"))
        #expect(HotkeyDisplay.isSupportedKey("keypad -"))
        #expect(HotkeyDisplay.isSupportedKey("globe"))
        #expect(HotkeyDisplay.isSupportedKey("🌐"))
        #expect(HotkeyDisplay.isSupportedKey("🌐︎"))
        #expect(HotkeyDisplay.isSupportedKey("cmd+shift+space"))
        #expect(HotkeyDisplay.isSupportedKey("cmd shift space"))
        #expect(HotkeyDisplay.isSupportedKey("cmd\u{00A0}shift\u{00A0}space"))
        #expect(HotkeyDisplay.isSupportedKey("meta+space"))
        #expect(HotkeyDisplay.isSupportedKey("super-shift-f6"))
        #expect(HotkeyDisplay.isSupportedKey("command-shift-page-down"))
        #expect(HotkeyDisplay.isSupportedKey("⌘ + ⇧ + f6"))
        #expect(HotkeyDisplay.isSupportedKey("⌘＋⇧＋space"))
        #expect(HotkeyDisplay.isSupportedKey("cmd, shift, space"))
        #expect(HotkeyDisplay.isSupportedKey("command/shift/space"))
        #expect(HotkeyDisplay.isSupportedKey("⌘⇧space"))
        #expect(HotkeyDisplay.isSupportedKey("⌃⌥return"))
        #expect(HotkeyDisplay.isSupportedKey("commandshiftspace"))
        #expect(HotkeyDisplay.isSupportedKey("ctrlaltdelete"))
        #expect(HotkeyDisplay.isSupportedKey("return or enter"))
        #expect(HotkeyDisplay.isSupportedKey("enter-or-return"))
        #expect(HotkeyDisplay.isSupportedKey("backquote"))
        #expect(HotkeyDisplay.isSupportedKey("quote left"))
        #expect(!HotkeyDisplay.isSupportedKey(""))
        #expect(HotkeyDisplay.isSupportedKey("capslock"))
        #expect(HotkeyDisplay.isSupportedKey("caps lock"))
        #expect(!HotkeyDisplay.isSupportedKey("foo"))
    }

    @Test
    func hotkeyCanonicalAliases() {
        #expect(HotkeyDisplay.canonicalKey("spacebar") == "space")
        #expect(HotkeyDisplay.canonicalKey("space key") == "space")
        #expect(HotkeyDisplay.canonicalKey("tab key") == "tab")
        #expect(HotkeyDisplay.canonicalKey("␣") == "space")
        #expect(HotkeyDisplay.canonicalKey("enter") == "return")
        #expect(HotkeyDisplay.canonicalKey("return key") == "return")
        #expect(HotkeyDisplay.canonicalKey("↩") == "return")
        #expect(HotkeyDisplay.canonicalKey("↵") == "return")
        #expect(HotkeyDisplay.canonicalKey("⏎") == "return")
        #expect(HotkeyDisplay.canonicalKey("esc") == "escape")
        #expect(HotkeyDisplay.canonicalKey("esc key") == "escape")
        #expect(HotkeyDisplay.canonicalKey("⎋") == "escape")
        #expect(HotkeyDisplay.canonicalKey("␛") == "escape")
        #expect(HotkeyDisplay.canonicalKey("delete key") == "delete")
        #expect(HotkeyDisplay.canonicalKey("backspace") == "delete")
        #expect(HotkeyDisplay.canonicalKey("⌫") == "delete")
        #expect(HotkeyDisplay.canonicalKey("⌦") == "forwarddelete")
        #expect(HotkeyDisplay.canonicalKey("insert") == "insert")
        #expect(HotkeyDisplay.canonicalKey("insert key") == "insert")
        #expect(HotkeyDisplay.canonicalKey("ins") == "insert")
        #expect(HotkeyDisplay.canonicalKey("help") == "help")
        #expect(HotkeyDisplay.canonicalKey("help key") == "help")
        #expect(HotkeyDisplay.canonicalKey("section") == "section")
        #expect(HotkeyDisplay.canonicalKey("§") == "section")
        #expect(HotkeyDisplay.canonicalKey("caps") == "capslock")
        #expect(HotkeyDisplay.canonicalKey("caps lock") == "capslock")
        #expect(HotkeyDisplay.canonicalKey("caps-lock") == "capslock")
        #expect(HotkeyDisplay.canonicalKey("globe") == "fn")
        #expect(HotkeyDisplay.canonicalKey("🌐") == "fn")
        #expect(HotkeyDisplay.canonicalKey("🌐︎") == "fn")
        #expect(HotkeyDisplay.canonicalKey("←") == "left")
        #expect(HotkeyDisplay.canonicalKey("left arrow") == "left")
        #expect(HotkeyDisplay.canonicalKey("→") == "right")
        #expect(HotkeyDisplay.canonicalKey("right arrow") == "right")
        #expect(HotkeyDisplay.canonicalKey("↑") == "up")
        #expect(HotkeyDisplay.canonicalKey("↓") == "down")
        #expect(HotkeyDisplay.canonicalKey("left key") == "left")
        #expect(HotkeyDisplay.canonicalKey("home key") == "home")
        #expect(HotkeyDisplay.canonicalKey("end key") == "end")
        #expect(HotkeyDisplay.canonicalKey("page-up") == "pageup")
        #expect(HotkeyDisplay.canonicalKey("pg up key") == "pageup")
        #expect(HotkeyDisplay.canonicalKey("pg dn key") == "pagedown")
        #expect(HotkeyDisplay.canonicalKey("⇞") == "pageup")
        #expect(HotkeyDisplay.canonicalKey("⇟") == "pagedown")
        #expect(HotkeyDisplay.canonicalKey("pg down") == "pagedown")
        #expect(HotkeyDisplay.canonicalKey("page down") == "pagedown")
        #expect(HotkeyDisplay.canonicalKey("numpad0") == "keypad0")
        #expect(HotkeyDisplay.canonicalKey("kp0") == "keypad0")
        #expect(HotkeyDisplay.canonicalKey("num9") == "keypad9")
        #expect(HotkeyDisplay.canonicalKey("numpad enter") == "keypadenter")
        #expect(HotkeyDisplay.canonicalKey("numpad .") == "keypaddecimal")
        #expect(HotkeyDisplay.canonicalKey("numpad ,") == "keypadcomma")
        #expect(HotkeyDisplay.canonicalKey("numpad +") == "keypadplus")
        #expect(HotkeyDisplay.canonicalKey("numpad clear") == "keypadclear")
        #expect(HotkeyDisplay.canonicalKey("clear") == "keypadclear")
        #expect(HotkeyDisplay.canonicalKey("⌧") == "keypadclear")
        #expect(HotkeyDisplay.canonicalKey("keypad -") == "keypadminus")
        #expect(HotkeyDisplay.canonicalKey("cmd+shift+space") == "space")
        #expect(HotkeyDisplay.canonicalKey("cmd shift space") == "space")
        #expect(HotkeyDisplay.canonicalKey("cmd\u{00A0}shift\u{00A0}space") == "space")
        #expect(HotkeyDisplay.canonicalKey("meta+space") == "space")
        #expect(HotkeyDisplay.canonicalKey("super-shift-f6") == "f6")
        #expect(HotkeyDisplay.canonicalKey("command-shift-page-down") == "pagedown")
        #expect(HotkeyDisplay.canonicalKey("⌘ + ⇧ + f6") == "f6")
        #expect(HotkeyDisplay.canonicalKey("⌘＋⇧＋space") == "space")
        #expect(HotkeyDisplay.canonicalKey("cmd, shift, space") == "space")
        #expect(HotkeyDisplay.canonicalKey("command/shift/space") == "space")
        #expect(HotkeyDisplay.canonicalKey("⌘⇧space") == "space")
        #expect(HotkeyDisplay.canonicalKey("⌃⌥return") == "return")
        #expect(HotkeyDisplay.canonicalKey("commandshiftspace") == "space")
        #expect(HotkeyDisplay.canonicalKey("ctrlaltdelete") == "delete")
        #expect(HotkeyDisplay.canonicalKey("return or enter") == "return")
        #expect(HotkeyDisplay.canonicalKey("enter-or-return") == "return")
        #expect(HotkeyDisplay.canonicalKey("backquote") == "backtick")
        #expect(HotkeyDisplay.canonicalKey("quote left") == "backtick")
        #expect(HotkeyDisplay.canonicalKey("grave key") == "backtick")
        #expect(HotkeyDisplay.canonicalKey("=") == "equals")
        #expect(HotkeyDisplay.canonicalKey("/") == "slash")
        #expect(HotkeyDisplay.canonicalKey("\\") == "backslash")
        #expect(HotkeyDisplay.canonicalKey(";") == "semicolon")
        #expect(HotkeyDisplay.canonicalKey("[") == "openbracket")
        #expect(HotkeyDisplay.canonicalKey("]") == "closebracket")
        #expect(HotkeyDisplay.canonicalKey("`") == "backtick")
    }

    @Test
    func hotkeyDisplayForKeypadKeys() {
        #expect(HotkeyDisplay.displayKey("keypad0") == "Num0")
        #expect(HotkeyDisplay.displayKey("numpadplus") == "Num+")
        #expect(HotkeyDisplay.displayKey("keypadcomma") == "Num,")
        #expect(HotkeyDisplay.displayKey("keypadenter") == "NumEnter")
        #expect(HotkeyDisplay.displayKey("return") == "Return/Enter")
        #expect(HotkeyDisplay.displayKey("insert") == "Insert")
        #expect(HotkeyDisplay.displayKey("help") == "Help")
        #expect(HotkeyDisplay.displayKey("section") == "§")
        #expect(HotkeyDisplay.displayKey("fn") == "Fn/Globe")
        #expect(HotkeyDisplay.displayKey("equals") == "=/+")
    }
}
